import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Currency Checker',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className='min-h-screen relative'>
        <Header />
        <main className='flex flex-col items-center p-24'>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
